from __future__ import annotations

PIP_SIZE = 0.01
JPY_PAIR_DECIMALS = 3
OANDA_MARGIN_RATE = 0.04
DEFAULT_SUPPORTED_MARKET_TIMEZONES = ("Asia/Tokyo", "Europe/London")
DEFAULT_TRADE_STATE_TTL_DAYS = 180
TRIGGER_CONDITION_BID = "BID"
TRIGGER_CONDITION_ASK = "ASK"
