#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT_DIR}/source_docs"

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

copy_doc() {
  local src="$1"
  local dst="$2"
  if [[ ! -f "${ROOT_DIR}/${src}" ]]; then
    echo "[WARN] missing: ${src}" >&2
    return
  fi
  cp "${ROOT_DIR}/${src}" "${OUT_DIR}/${dst}"
  echo "${dst} <- ${src}"
}

cat > "${OUT_DIR}/MANIFEST.md" <<'EOF'
# ChatGPT Source Docs

This directory is generated by `tools/collect_chatgpt_sources.sh`.
Upload these files to the ChatGPT-side source context when running qualify / scan review threads.

EOF

copy_doc "README.md" "top_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "docs/FX_Research_Constitution.md" "docs_FX_Research_Constitution.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "docs/Unit_Level_Policy.md" "docs_Unit_Level_Policy.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "runtime/README.md" "runtime_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "runtime/Spec.md" "runtime_Spec.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "src/timer_entry/README.md" "timer_entry_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "src/timer_entry/Spec.md" "timer_entry_Spec.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "src/timer_entry/filters.py" "timer_entry_filters.py" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "src/timer_entry/schemas.py" "timer_entry_schemas.py" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "scan/README.md" "scan_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "qualify/README.md" "qualify_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "qualify/Spec.md" "qualify_Spec.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "qualify/results/README.md" "qualify_results_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "qualify/docs/Audit_Result.md" "qualify_docs_Audit_Result.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "qualify/docs/Ops.md" "qualify_docs_Ops.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "portfolio/README.md" "portfolio_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "portfolio/Spec.md" "portfolio_Spec.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "ops/README.md" "ops_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "ops/Spec.md" "ops_Spec.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "ops/docs/Dashboard_UI.md" "ops_docs_Dashboard_UI.md" | tee -a "${OUT_DIR}/MANIFEST.md"
copy_doc "ops/web/README.md" "ops_web_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"

copy_doc "src/timer_entry/prompts/README.md" "timer_entry_prompts_README.md" | tee -a "${OUT_DIR}/MANIFEST.md"

echo
echo "[DONE] copied ChatGPT source docs to ${OUT_DIR}"
